# Generated by Django 4.2 on 2025-09-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_alter_category_options_videointerval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='embedding_model_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
