# Generated by Django 4.2 on 2025-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_category_embedding_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_prompt',
            field=models.TextField(blank=True, help_text='Prompt personalizzato per descrivere i keyframe delle immagini. Se vuoto viene utilizzato il prompt di default.', max_length=2000),
        ),
        migrations.AddField(
            model_name='category',
            name='text_prompt',
            field=models.TextField(blank=True, help_text='Prompt personalizzato per la pulizia dei testi trascritti. Se vuoto viene utilizzato il prompt di default.', max_length=2000),
        ),
    ]
