# Generated by Django 4.2 on 2025-09-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='videos.category'),
        ),
    ]
